volumes:
  shared-data:

services:
  nutrisnap-preprocess:
    build:
      context: .
      dockerfile: Dockerfile.preprocess
    container_name: ns-preprocess
    env_file:
      - .env
    volumes:
      - shared-data:/app/data
      - ./cache:/root/.cache
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nutrisnap-training:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: ns-train
    env_file:
      - .env
    volumes:
      - shared-data:/app/data
      - ./output:/app/food101-vit-model
      - ./cache:/root/.cache
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true