volumes:
  shared-data:

services:
  nutrisnap-preprocess:
    build:
      context: .
      dockerfile: preprocess/Dockerfile
    container_name: ns-preprocess
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa.json
    env_file:
      - .env
    volumes:
      - shared-data:/app/data
      - ./cache:/root/.cache
      - ../secrets/nutrisnap-sa.json:/secrets/sa.json:ro
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nutrisnap-training:
    build:
      context: .
      dockerfile: train/Dockerfile
    container_name: ns-train
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa.json
    env_file:
      - .env
    volumes:
      - shared-data:/app/data
      - ./output:/app/food101-vit-model
      - ./cache:/root/.cache
      - ../secrets/nutrisnap-sa.json:/secrets/sa.json:ro
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true